name = "TriangularReshapes"
uuid = "d3851a89-a5b6-4c9e-9e01-516a6ef5a432"
authors = ["Algopaul <72927083+Algopaul@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
